version: '3.4'

services:
  train1:
    #image: ${DOCKER_REGISTRY-}train1
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${APP_PORT}:80
    depends_on:
          - db
  db:
    container_name: sql-server-db
    #image: "mcr.microsoft.com/mssql/server:2019-latest"
    build: 
       context: ./database/
    #  context: .
      #dockerfile: database/Dockerfile
    #args:
    #  - SA_PASSWORD=$SA_PASSWORD
    ports:
      - ${DB_PORT}:1433
    environment:
      - SA_PASSWORD=OneThing$123
      - ACCEPT_EULA=Y